#!/usr/bin/env php
<?php
require_once dirname (__FILE__) . '/../libs/prepend.php';

$c = new CLIHelper();

if (!Database::is_enabled())
{
	$c->writeln('The database is disabled.');
}

$users = Model::get_users();
$c->writeln(count($users) . ' user(s).');
foreach ($users as $user)
{
	$c->writeln($user->id . "\t" . $user->name . "\t" . $user->email . "\t"
		. ACL::to_string($user->permission));
}

